cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:product_slug>/', views.cart_remove, name='cart_remove'),
]

star_wars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls

urlpatterns = [
    path('ajax_select/', include(ajax_select_urls)),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('games/', include('games.urls')),
    path('books/', include('books.urls')),
    path('serials/', include('serials.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('favorites/', include('favorites.urls')),
    path('', include('main_page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'star_wars.views.handler404'

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int, label="Количество")
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput,
                                label="Обновить")

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from accounts.models import Profile
from books.models import Book
from games.models import Game
from movies.models import Movie
from serials.models import Serial
from .cart import Cart
from .forms import CartAddProductForm


def get_product(request, product_slug):
    if str(request).split('/')[-2] in list(Movie.objects.all().values_list('slug', flat=True)):
        return get_object_or_404(Movie, slug=product_slug)
    elif str(request).split('/')[-2] in list(Game.objects.all().values_list('slug', flat=True)):
        return get_object_or_404(Game, slug=product_slug)
    elif str(request).split('/')[-2] in list(Book.objects.all().values_list('slug', flat=True)):
        return get_object_or_404(Book, slug=product_slug)
    elif str(request).split('/')[-2] in list(Serial.objects.all().values_list('slug', flat=True)):
        return get_object_or_404(Serial, slug=product_slug)


@require_POST
def cart_add(request, product_slug):
    cart = Cart(request)
    product = get_product(request, product_slug)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    if request.user.id is not None:
        profile = Profile.objects.get(user=request.user)
        profile.cart_data = request.session['cart']
        profile.save()
    return redirect('cart:cart_detail')


def cart_remove(request, product_slug):
    cart = Cart(request)
    product = get_product(request, product_slug)
    cart.remove(product)
    if request.user.id is not None:
        profile = Profile.objects.get(user=request.user)
        profile.cart_data = request.session['cart']
        profile.save()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Корзина покупок
{% endblock %}

{% block content %}
<h1>Корзина покупок</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.poster %}{{ product.poster.url }} {% else %}{% static 'img/no_image.png' %}{% endif %}"
                     alt="" height="200" width="150">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.slug %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
            </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.slug %}">Удалить</a></td>
        <td>
            {{ item.quantity }}
        </td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
{% if cart.get_total_price %}
<a href="{% url 'order_create' %}" class="button">Checkout</a>
{% endif %}
{% endblock %}